Draft : Feature/vmray enrichment connector
Sqooba/connectors pull request #23
Opened 2022-05-04 13:49 UTC by yanover

### Proposed changes
Implementation of an enrichment connector in order to process VMRay analysis.
An analysis is trigger from the opencti platform (on-demand).

2022-05-05 07:23 UTC, debelyoo requested changes

2022-05-05 07:23 UTC, debelyoo commented on internal-enrichment/vmray/src/tests/test_builder.py
> +        Test create_openctitext function, the result should be equal to the stix_expected variable's field
incomplete test

2022-05-05 07:23 UTC, debelyoo commented on internal-enrichment/vmray/src/vmray/builder.py
> +        self.log("===== CREATE_FILE =====")
What kind of log level is that ?

2022-05-05 07:23 UTC, debelyoo commented on internal-enrichment/vmray/src/vmray/constants.py
> +"""Constants for DT-Lookup."""
bad copy/paste

2022-05-05 07:23 UTC, debelyoo commented on internal-enrichment/vmray/src/vmray/constants.py
> +CONTACTS_TYPE = {
I guess these are useless

2022-05-05 07:23 UTC, debelyoo commented on internal-enrichment/vmray/src/vmray/vmray.py
> +                        self.helper.log_error(f"[VMRay] An error occured during the builder initialization : {e}")
typo: `occured` --> `occurred`

2022-05-05 07:23 UTC, debelyoo commented on internal-enrichment/vmray/src/vmray/vmray.py
> +                                        f"[VMRay] An error occured will generating STIX entity of type {sco['key']} with error : {e}"
typo: `will` --> `while`

2022-05-05 07:23 UTC, debelyoo commented on internal-enrichment/vmray/src/vmray/vmray.py
> +                                self.helper.log_debug(f"YARA_RULE: {yara_rule}")
maybe a trace would be more appropriate

2022-05-05 07:23 UTC, debelyoo commented on internal-enrichment/vmray/src/vmray/vmray.py
> +                    with open("bundle.json", 'w') as f:
that is for debugging purpose only, right ?

2022-05-05 07:23 UTC, debelyoo commented on internal-enrichment/vmray/src/vmray/yara_fetcher.py
> +    def yara_to_stix_indicator(self, rule_desc: str, ruleset_name: str, ruleset_id: str, yara: dict, creator: Identity, run_on_s: bool) -> Indicator:
this method is not used anymore, right ? replaced by `create_yara_indicator()`

2022-05-05 07:23 UTC, debelyoo commented on internal-enrichment/vmray/src/vmray/builder.py
> +        id: str
I would have used `ruleset_id` and `ruleset_name` for the parameters (for clarity)

2022-05-05 07:35 UTC, yanover commented on internal-enrichment/vmray/src/tests/test_builder.py
> +    A connection to an OpenCti instance (API + RAMQ) must exist to run the tests.
No, it is not the case anymore. The builder does not depends on any external ressource. I've refactor this comment.

2022-05-05 07:37 UTC, debelyoo commented on internal-enrichment/vmray/src/vmray/vmray.py
> +                            validity = self.helper.api.stix2.format_date(datetime.now())
we should set the analysis creation date here (not the current date)

2022-05-05 07:45 UTC, yanover commented on internal-enrichment/vmray/src/vmray/builder.py
> +        self.log("===== CREATE_FILE =====")
This will depend what you pass to the VMRAYBuilder's logger variable:

For example, in the vmray.py, the method pass to this variable is the log_debug method provide by the OpenCtiConnectorHelper :

vmray.py
```python
# Set the logger method to the builder
builder.logger = self.helper.log_info
```

And in the test_builder, as we don't have the API, we use the python' logging module with a DEBUG level :

test_builder.py
```python
# Pass a valid logger to the builder
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
self.builder.logger = logging.debug
```

2022-05-05 07:56 UTC, debelyoo commented on internal-enrichment/vmray/src/vmray/builder.py
> +        self.log("===== CREATE_FILE =====")
ok I see. Generally we don't use logging for the tests. Maybe when you "debug the tests" but once they are working as expected logging is useless in unit tests. So I would not do anything specific in the code to enable logging in unit tests.

2022-05-05 11:41 UTC, yanover commented on internal-enrichment/vmray/src/vmray/vmray.py
> +                    with open("bundle.json", 'w') as f:
Yes, correct. It will be removed when the debug session will be done.

2022-05-05 11:57 UTC, debelyoo commented on internal-enrichment/vmray/src/vmray/builder.py
> +                "The analysis sent to the builder does not respect the type define, field 'analyse_metada must be of type dict and field summary must be of type str'"
typos: `define` --> `defined`, `analyse_metada` --> `analysis_metadata`

2022-05-05 12:02 UTC, axelfahy commented
In my opinion, the `tests` should not be in the `src` folder. When creating the image, we are copying the whole `src` folder into the image and the tests are only increasing the size of the image and not usefull at runtime. 

This is usually the same for python packages, tests are separated to avoid shipping them with the package.

2022-05-05 12:19 UTC, axelfahy commented
All OpenCTI python code is formatted using [black](https://github.com/psf/black), it might be a good idea to do the same, even if this connector is not shared with the community. 

You can also run linters and code check such as [pylint](https://pylint.pycqa.org/en/latest/), [flake8](https://flake8.pycqa.org/en/latest/), [mypy](http://mypy-lang.org/) (if you are using python type hints) and [bandit](https://bandit.readthedocs.io/en/latest/). Not all warnings are relevant, but some might still be useful.

2022-05-05 12:22 UTC, yanover commented on internal-enrichment/vmray/src/vmray/constants.py
> +CONTACTS_TYPE = {
Correct, I removed it

2022-05-05 12:23 UTC, yanover commented on internal-enrichment/vmray/src/vmray/yara_fetcher.py
> +    def yara_to_stix_indicator(self, rule_desc: str, ruleset_name: str, ruleset_id: str, yara: dict, creator: Identity, run_on_s: bool) -> Indicator:
Correct, I removed this chunk of code from the yara_fetcher.py file

2022-05-05 12:29 UTC, yanover commented on internal-enrichment/vmray/src/vmray/builder.py
> +                "The analysis sent to the builder does not respect the type define, field 'analyse_metada must be of type dict and field summary must be of type str'"
Sorry, I was thinking about the field 'sample_details', not analysis_metadata.
`The analysis sent to the builder does not respect the type defined, field 'sample_details' must be of type dict and field 'summary' must be of type str`

2022-05-05 14:08 UTC, axelfahy commented on internal-enrichment/vmray/src/vmray/builder.py
> +            labels = ""
I am not sure of the impact, but the `labels` are supposed to be a `ListProperty(StringProperty)` and this would only be a `StringProperty`. This seems to work however, the results are not the same compared to an empty list: 

Example with an empty list: 
`>>> Report(name="test-list", object_refs=[OpenCTIStix2Utils.generate_random_stix_id("file")], published=datetime.datetime.now(), labels=[])
Report(type='report', spec_version='2.1', id='report--4915045c-5db8-4682-abed-f46096c6396a', created='2022-05-05T14:05:44.496589Z', modified='2022-05-05T14:05:44.496589Z', name='test-list', published='2022-05-05T16:05:44.496574Z', object_refs=['file--748baece-cc7c-11ec-8366-acde48001122'], revoked=False)`

Example with an empty string: 
`>>> Report(name="test-string", object_refs=[OpenCTIStix2Utils.generate_random_stix_id("file")], published=datetime.datetime.now(), labels="")
Report(type='report', spec_version='2.1', id='report--0a7e562f-9410-49cd-8207-ad9ce8bda657', created='2022-05-05T14:06:37.809392Z', modified='2022-05-05T14:06:37.809392Z', name='test-string', published='2022-05-05T16:06:37.809379Z', object_refs=['file--94529376-cc7c-11ec-8366-acde48001122'], revoked=False, labels=[''])`

With the empty string, a `labels` field is created, and I don't know if this is what we want. 

Note: give an empty set will not work and a `stix2.exceptions.InvalidValueError` is raised, it must be an empty list.

2022-05-05 14:08 UTC, axelfahy commented on internal-enrichment/vmray/src/vmray/builder.py
> +        # COntrol label field
typo

2022-05-05 14:09 UTC, axelfahy commented on internal-enrichment/vmray/src/vmray/builder.py
> +        print(obj_report)
`print` should be removed in prod.

2022-05-05 14:10 UTC, axelfahy commented on internal-enrichment/vmray/src/vmray/constants.py
> +STATIC_DATA_FIELD = [
`STATIC_DATA_FIELD` and `BLACKLIST_DOMAIN` can be sets, you can replace `[]` by `{}`.

2022-05-05 14:17 UTC, axelfahy commented on internal-enrichment/vmray/src/vmray/builder.py
> +    def log(self, msg: str) -> None:
If if don't define the `self.logger` manually, we won't have any logs?

2022-05-05 14:38 UTC, axelfahy commented on internal-enrichment/vmray/src/tests/test_builder.py
> +    def setUpClass(self):
Should be `cls` instead of `self` since its a class method.

2022-05-06 06:32 UTC, yanover commented on internal-enrichment/vmray/src/tests/test_builder.py
> +        Test create_openctitext function, the result should be equal to the stix_expected variable's field
This test is now implemented

2022-05-06 06:39 UTC, yanover commented on internal-enrichment/vmray/src/tests/test_builder.py
> +            with open("tests/ressources/report_str.json", 'w') as str_file:
This file is actually generated by the setUpClass. The tester can thus work with the report_dict file, which is a large dictionary and therefore more easily manipulated than the report_str file which contains the summary in string format (mandatory format for the builder).

This is correct, this file must be deleted between each test and regenerated. The current behavior can be dangerous because the report_str file is available for modification.

2022-05-06 07:36 UTC, yanover commented on internal-enrichment/vmray/src/vmray/builder.py
> +        if type(analysis) is dict and type(analysis["sample_details"] is dict and type(analysis["summary"]) is str):
Thank you for the comment, according to the post you shared, I've made the change

2022-05-06 07:47 UTC, yanover commented on internal-enrichment/vmray/src/vmray/builder.py
> +            if analysis.get("summary", None) is None or analysis.get("sample_details") is None:
According to those decisions :
- The "sample_details" key must be a non empty dictionnary
- The "summary" key must be a non-empty string

I wanted an optimal way to test all possibilities, i've used the `if not` conditional statement to test my analysis : 

```
if isinstance(analysis, dict) and isinstance(analysis["sample_details"], dict) and isinstance(analysis["summary"], str):
    if not analysis.get("summary") or not analysis.get("sample_details"):
        raise KeyError("...")
    else:
        raise TypeError("...")
```

With the get implementation `if analysis.get("summary")`, an empty string is not evaluated as None and the test fails.

2022-05-06 07:56 UTC, yanover commented on internal-enrichment/vmray/src/vmray/builder.py
> +            labels = ""
You are right, by the way, the stix library returned errors when the set was empty
We have now converted this value to a list.
```python
obj_report = Report(
    ....
    labels=list(labels),
    ...
)
```

2022-05-06 08:09 UTC, debelyoo commented on internal-enrichment/vmray/src/vmray/builder.py
> +        description = f"{description}. (Ruleset | name: {ruleset_name}, id: {ruleset_id})"
if `description` is an empty string you should only display `(Ruleset | name: {ruleset_name}, id: {ruleset_id})`

2022-05-06 08:14 UTC, debelyoo commented on internal-enrichment/vmray/src/vmray/builder.py
> +        self.log("===== CREATE_IP =====")
All these logs (e.g. ===== CREATE XXX =====) should be in `trace` level

2022-05-06 09:04 UTC, debelyoo requested changes

2022-05-06 09:04 UTC, debelyoo commented on internal-enrichment/vmray/src/vmray/builder.py
> +            custom_properties=self.custom_props,
`confidence` is missing

2022-05-06 12:34 UTC, yanover commented on internal-enrichment/vmray/src/vmray/vmray.py
> +                                self.helper.log_debug(f"YARA_RULE: {yara_rule}")
This log level does not exist on the OpenCtiConnectorHelper : 

```python
class OpenCTIConnectorHelper:

    ...

    def log_error(self, msg: str) -> None:
        logging.error(msg)

    def log_info(self, msg: str) -> None:
        logging.info(msg)

    def log_debug(self, msg: str) -> None:
        logging.debug(msg)

    def log_warning(self, msg: str) -> None:
        logging.warning(msg)
        
    ...        

```

2022-05-06 13:15 UTC, yanover commented on internal-enrichment/vmray/src/vmray/es_client.py
> +        # Drop the ending slash if present.
Yes correct, I've deleted this comment

2022-05-06 13:15 UTC, yanover commented on internal-enrichment/vmray/src/vmray/es_client.py
> +        JSON or None
This comment has been updated according to the return value specified in the method's signature.

2022-05-10 05:56 UTC, yanover commented on internal-enrichment/vmray/src/vmray/vmray.py
> +                            validity = self.helper.api.stix2.format_date(datetime.now())
This modification has been implemented.

2022-05-10 08:21 UTC, axelfahy commented on internal-enrichment/vmray/src/vmray/builder.py
> +    def log(self, msg: str) -> None:
Good, it seems better to use directly the logger from OpenCTI.

2022-05-12 05:53 UTC, debelyoo commented on internal-enrichment/vmray/src/vmray/constants.py
> +    "EMAIL_MESSAGE": {"key": "emails", "transform": "create_email_message"},
this should be part of the next PR, no ?

2022-05-12 05:53 UTC, debelyoo commented on internal-enrichment/vmray/src/vmray/constants.py
> +    INIT_ERROR = "[{}] - An error occured during the {} initialization"
typo: `occured` --> `occurred` (multiple times in the code)

2022-05-12 05:56 UTC, debelyoo commented on internal-enrichment/vmray/docker-compose.yml
> +    image: opencti/connector-vmray:5.2.4
image should be `5.2.4-sqb-6.1.0`

2022-05-12 06:06 UTC, debelyoo commented on internal-enrichment/vmray/src/vmray/builder.py
> +            self.helper.log_info(
set `debug` level for that

2022-05-12 06:06 UTC, debelyoo commented on internal-enrichment/vmray/src/vmray/builder.py
> +        This method remove 'http://', 'https://' and 'www.' in the url parameter.\n
Are these `\n` necessary in the comments ? (multiple times in the code)

2022-05-12 06:16 UTC, debelyoo commented on internal-enrichment/vmray/src/vmray/builder.py
> +            or domain_name in BLACKLIST_DOMAIN
I would separate the handling of invalid domains and blacklisted domains. Invalid domains may generate an error but not the domains that are blacklisted.

Is this code `not domain_name` checking that the value of `domain_name` is not empty (empty string) ?

2022-05-12 06:16 UTC, yanover commented on internal-enrichment/vmray/src/vmray/constants.py
> +    "EMAIL_MESSAGE": {"key": "emails", "transform": "create_email_message"},
Yes, that's right. This line must be deleted.

2022-05-12 06:25 UTC, debelyoo commented on internal-enrichment/vmray/src/vmray/builder.py
> +        # if not validators.email(email["email_address"]):
Can we remove this code ?

2022-05-12 07:27 UTC, yanover commented on internal-enrichment/vmray/src/vmray/builder.py
> +        This method remove 'http://', 'https://' and 'www.' in the url parameter.\n
According to our previous discussion, I have removed these line breaks.

2022-05-12 07:31 UTC, yanover commented on internal-enrichment/vmray/src/vmray/builder.py
> +        # if not validators.email(email["email_address"]):
Yes I removed this line, email validation will eventually be a future feature. The email addresses stored in the analysis are for the moment in a non-uniform format, we will for the moment keep the raw string (for comparison purposes).

2022-05-12 09:56 UTC, yanover commented on internal-enrichment/vmray/src/vmray/constants.py
> +# Be careful, the order matters
Yes that's correct, [Dict keeps insertion order](https://mail.python.org/pipermail/python-dev/2017-December/151283.html).

In this case, if the dictionary is declared in a different order, the iterative process that calls the functions that generates the SCOs will call the functions responsible for these treatments in a different order.

Therefore, some functions depend on the content of the bundle to work, if the functions for creating SCOs are not called in a defined order, this could make the enrichment wrong.

This behaviour should not be observed for the current calls, but will become effective as soon as the mail processing is implemented.

2022-05-12 13:08 UTC, axelfahy commented on internal-enrichment/vmray/tests/test_builder.py
> +        if os.path.exists(cls.report_str):
nitpick: the `pathlib` lib is pretty neat to handle path and file manipulations, such as `Path(cls.report_str).unlink(missing_ok=True)`

2022-05-12 13:25 UTC, axelfahy commented on internal-enrichment/vmray/src/vmray/builder.py
> +        type: str
`stix_type`

2022-05-12 13:53 UTC, axelfahy commented on internal-enrichment/vmray/src/vmray/vmray.py
> +                        self.helper.metric_inc["client_error_count"]
Should be parenthesis: `self.helper.metric_inc("client_error_count")`

2022-05-12 13:55 UTC, axelfahy commented on internal-enrichment/vmray/src/vmray/builder.py
> +    ) -> Union[StixDomainObject, StixCyberObservable]:
Could be `None` if we don't find the key, and we could have a `return` statement after the loop

2022-05-12 13:56 UTC, axelfahy commented on internal-enrichment/vmray/src/vmray/es_client.py
> +    def search(self, sha: str, stixFile: EntityType) -> JSONType:
Is there a reason for having `stixFile` (camelcase) and not `stix_file` (snake_case), like the other variables?

2022-05-12 13:58 UTC, axelfahy commented on internal-enrichment/vmray/src/vmray/yara_fetcher.py
> +    def get_rule_key(self, ruleset_id: str, rule_name: str) -> str:
`self` is not use, this should be a static method (add `@staticmethod`)

2022-05-12 14:00 UTC, axelfahy commented on internal-enrichment/vmray/tests/test_builder.py
> +        assert not "description" in stix_result
Not sure if this works, usually, it is: `"description" not in strix_result`

2022-05-12 14:04 UTC, axelfahy commented on internal-enrichment/vmray/tests/test_builder.py
> +        with open(cls.report_dict, "r") as dict_file:
nitpick: specify the encoding in the `open` function.

2022-05-12 14:04 UTC, axelfahy commented on internal-enrichment/vmray/tests/test_builder.py
> +            with open(cls.report_str, "w") as str_file:
nitpick: specify the encoding in the `open` function.

2022-05-12 14:04 UTC, axelfahy commented on internal-enrichment/vmray/tests/test_builder.py
> +        with open(cls.report_str, "r") as analysis:
nitpick: specify the encoding in the `open` function.

2022-05-12 14:16 UTC, axelfahy commented on internal-enrichment/vmray/src/vmray/builder.py
> +        self.object_refs: list(RelationshipRef) = []
Types should be in brackets: `list[RelationshipRef]`, if this is not possible with the `list`, it is with `List` from typing.

2022-05-12 14:18 UTC, axelfahy commented on internal-enrichment/vmray/src/vmray/builder.py
> +        Raise
Can be remove, the method does not raise an error.

2022-05-12 14:18 UTC, axelfahy commented on internal-enrichment/vmray/src/vmray/builder.py
> +        target_id: RelationshipRef
Wrong variable name in docstring.

2022-05-12 14:19 UTC, axelfahy commented on internal-enrichment/vmray/src/vmray/builder.py
> +        # Replace www. if it exist in the string
Typo: exists

2022-05-12 14:19 UTC, axelfahy commented on internal-enrichment/vmray/src/vmray/builder.py
> +            * www.test.com --> test.comu
Typo: comu

2022-05-12 14:24 UTC, axelfahy commented on internal-enrichment/vmray/src/vmray/vmray.py
> +                        self.helper.metric_inc("client_error_count")
Are we not counting the error twice? If the bundle is None, that means that it was not created correctly and has already raise an exception, and already been counted.

2022-05-12 21:27 UTC, yanover commented on internal-enrichment/vmray/src/vmray/builder.py
> +        self.object_refs: list(RelationshipRef) = []
Yes, nice catch. According to [this page](https://docs.python.org/3/library/typing.html), list type should be in bracket.

2022-05-12 21:30 UTC, yanover commented on internal-enrichment/vmray/tests/test_builder.py
> +        with open("ressources/yara.json", "r") as f:
I did the changes.

2022-05-12 21:32 UTC, yanover commented on internal-enrichment/vmray/src/vmray/es_client.py
> +    def search(self, sha: str, stixFile: EntityType) -> JSONType:
Not really, thank you for the comment, I did the change.

2022-05-12 21:37 UTC, yanover commented on internal-enrichment/vmray/src/vmray/builder.py
> +    ) -> Union[StixDomainObject, StixCyberObservable]:
That's right, this function should now only return StixCyberObservable or None.
I have changed the signature of this function according to this need.

`def find_from_bundle(self, stix_type: str, key: str, value: str) -> Union[StixCyberObservable, None]:`

2022-05-13 05:22 UTC, debelyoo approved these changes

2022-05-13 05:59 UTC, yanover commented on internal-enrichment/vmray/tests/test_builder.py
> +        assert not "description" in stix_result
After verification, the two forms make identical bytecode, the check result would be the same. However, I also find the form `if x not in` clearer to read. Thanks for the pointer.

2022-05-13 06:03 UTC, yanover commented on internal-enrichment/vmray/tests/test_builder.py
> +        if os.path.exists(cls.report_str):
Thank for the tip !

2022-05-13 06:49 UTC, yanover commented on internal-enrichment/vmray/src/vmray/vmray.py
> +                        self.helper.metric_inc("client_error_count")
Yes you're right, I changed the implementation.

Now, the blocs that generate the report and the bundle use the keyword `continue` in the except part, so the process does not go forward if an error occurred.

According to the send_stix2_bundle docs, we now catch `ValueError` for empty Bundle (even if it should never appear) and all Exception for unknown behaviour.

Hope it sounds better.

2022-05-13 06:59 UTC, yanover commented on internal-enrichment/vmray/src/vmray/builder.py
> +    def __init__(self, author: Identity, run_on_s: bool, analysis: dict, helper: None):
No you're right, the type should be `helper: OpenCTIConnectorHelper`

2022-05-13 07:08 UTC, yanover commented on internal-enrichment/vmray/tests/test_builder.py
> +    def test_init_builder(cls):
This is a misunderstanding of the keyword **self** and **cls** on my side.

> cls refers to the class, whereas self refers to the instance. Using the cls keyword, we can only access the members of the class, whereas using the self keyword, we can access both the instance variables and the class attributes.

Thanks for the pointer ! I will make the change.

2022-05-13 08:30 UTC, axelfahy commented on internal-enrichment/vmray/src/vmray/builder.py
> +        self.object_refs: list(RelationshipRef) = []
What I meant is that I am not sure if this will work: 
`self.objects_refs: list[RelationshipRef] = []`
and if it does not, this should work: 
```
from typing import List
self.object_refs: List[RelationshipRef] = []
```

list vs List

2022-05-13 08:36 UTC, axelfahy commented on internal-enrichment/vmray/src/vmray/builder.py
> +        object_refs = [ref.target for ref in self.object_refs]
If you like one liner: `object_refs = [ref.target for ref in self.object_refs] + [self.sample_id]`

(if you don't, `append` is nice too).

2022-05-13 08:37 UTC, axelfahy approved these changes

2022-05-13 09:01 UTC, yanover commented on internal-enrichment/vmray/src/vmray/builder.py
> +        self.object_refs: list(RelationshipRef) = []
The previous code (with minus `list`) did not throw any Exception but after having carefully checked, the import from typing as you mentioned is the one used in the documentation.

2022-05-13 11:23 UTC, merged